### ISSUE TITLE
Build fails at test_setup_helpers.py with AttributeError

### ISSUE THREAD

**Issue by avilqu** [astropy/extension-helpers#24]
I can't build the AUR package python-extension-helpers on a fresh Archlinux install. I'm getting the following error output:

```
=========================================== FAILURES ===========================================
_____________________________________ test_compiler_module _____________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7f0e497ac5e0>
c_extension_test_package = local('/tmp/pytest-of-tan/pytest-2/test_compiler_module0/test_pkg')

    def test_compiler_module(capsys, c_extension_test_package):
        """
        Test ensuring that the compiler module is built and installed for packages
        that have extension modules.
        """
    
        test_pkg = c_extension_test_package
        install_temp = test_pkg.mkdir('install_temp')
    
        with test_pkg.as_cwd():
            # This is one of the simplest ways to install just a package into a
            # test directory
>           run_setup('setup.py',
                      ['install',
                       '--single-version-externally-managed',
                       '--install-lib={0}'.format(install_temp),
                       '--record={0}'.format(install_temp.join('record.txt'))])

build/lib/extension_helpers/tests/test_setup_helpers.py:159: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

setup_script = 'setup.py'
args = ['install', '--single-version-externally-managed', '--install-lib=/tmp/pytest-of-tan/pytest-2/test_compiler_module0/test_pkg/install_temp', '--record=/tmp/pytest-of-tan/pytest-2/test_compiler_module0/test_pkg/install_temp/record.txt']

    def run_setup(setup_script, args):
    
        # This used to call setuptools.sandbox's run_setup, but due to issues with
        # this and Cython (which caused segmentation faults), we now use subprocess.
    
        setup_script = os.path.abspath(setup_script)
    
        path = os.path.dirname(setup_script)
        setup_script = os.path.basename(setup_script)
    
        if HAS_COVERAGE:
    
            # In this case, we run the command using the coverage command and we
            # then collect the coverage data into a SUBPROCESS_COVERAGE list which
            # is set up at the start of the testing process and is then combined
            # into a single .coverage file at the end of the testing process.
    
            p = sp.Popen(['coverage', 'run', setup_script] + list(args), cwd=path,
                         stdout=sp.PIPE, stderr=sp.PIPE)
            stdout, stderr = p.communicate()
    
            cdata = CoverageData()
>           cdata.read_file(os.path.join(path, '.coverage'))
E           AttributeError: 'CoverageData' object has no attribute 'read_file'

build/lib/extension_helpers/tests/__init__.py:68: AttributeError
======================================= warnings summary =======================================
../../../../../../../usr/lib/python3.9/site-packages/packaging/version.py:127: 1286 warnings
  /usr/lib/python3.9/site-packages/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================== short test summary info ====================================
FAILED build/lib/extension_helpers/tests/test_setup_helpers.py::test_compiler_module - Attrib...
========================== 1 failed, 3 passed, 1286 warnings in 2.90s ==========================
Traceback (most recent call last):
  File "/usr/bin/pytest", line 33, in <module>
    sys.exit(load_entry_point('pytest==6.2.1', 'console_scripts', 'pytest')())
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 311, in wrap_session
    config._ensure_unconfigure()
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 987, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/tan/.cache/yay/python-extension-helpers/src/extension-helpers-0.1/build/lib/extension_helpers/conftest.py", line 57, in pytest_unconfigure
    combined_cdata.write_file('.coverage.subprocess')
AttributeError: 'CoverageData' object has no attribute 'write_file'
==> ERROR: A failure occurred in check().
    Aborting...
error making: python-extension-helpers

```

**Comment by embray** [comment]
Hi @avilqu .  It looks to me you have a newer version of the `coverage` module installed (`coverage>=5.0`) whereas the tests for extension-helpers apparently still requires `coverage<5`, and there were API changes between the two versions that make this break.

If using `coverage<5` is not feasible for the Arch package we could look into fixing those API compatibilities and bumping the allowed version of `coverage`.
